#!/usr/bin/env python
"""Generate original Xbox dashboard metadata from the checked-in UT icon."""

from __future__ import print_function

import codecs
import os
import subprocess
import sys

try:
    from PIL import Image
except ImportError:
    print("ERROR: Pillow is required to regenerate dashboard assets")
    sys.exit(1)


SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
XBOX_DIR = os.path.dirname(SCRIPT_DIR)
ASSET_DIR = os.path.join(XBOX_DIR, "XboxAssets")
SOURCE_ICON = os.path.join(ASSET_DIR, "ut99_icon.ico")
OUTPUT_INCLUDE = os.path.join(XBOX_DIR, "XboxLaunch", "Src", "XboxDashboardAssets.inc")
TITLE_NAME = "Unreal Tournament"


def find_bundler():
    candidates = (
        r"C:\XDK_5558\XDK\xbox\bin\bundler.exe",
        r"C:\XDK\xbox\bin\bundler.exe",
        r"C:\XDK\bin\bundler.exe",
    )
    for candidate in candidates:
        if os.path.isfile(candidate):
            return candidate
    raise RuntimeError("XDK bundler.exe was not found")


def write_bitmap(icon, size, name):
    available = icon.info.get("sizes", set())
    if (size, size) not in available:
        raise RuntimeError("Source ICO has no native {}x{} frame".format(size, size))
    frame = icon.ico.getimage((size, size)).convert("RGB")
    frame.save(os.path.join(ASSET_DIR, name), format="BMP")


def run_bundler(bundler, rdf_name):
    result = subprocess.call([bundler, os.path.join(ASSET_DIR, rdf_name)], cwd=ASSET_DIR)
    if result != 0:
        raise RuntimeError("bundler failed for {} with code {}".format(rdf_name, result))


def format_byte_array(name, data):
    lines = ["static const unsigned char {}[{}] = {{".format(name, len(data))]
    for offset in range(0, len(data), 12):
        chunk = data[offset:offset + 12]
        lines.append("    " + ", ".join("0x{:02X}".format(value) for value in bytearray(chunk)) + ",")
    lines.append("};")
    lines.append("static const unsigned int {}Size = {};".format(name, len(data)))
    return "\n".join(lines)


def write_embedded_assets():
    assets = (
        ("GXboxDashboardTitleMetaXbx", os.path.join(ASSET_DIR, "TitleMeta.xbx")),
        ("GXboxDashboardTitleImageXbx", os.path.join(ASSET_DIR, "titleimage.xbx")),
        ("GXboxDashboardSaveImageXbx", os.path.join(ASSET_DIR, "saveimage.xbx")),
    )
    blocks = ["// Generated by Tools/generate_dashboard_assets.py. Do not edit by hand."]
    for symbol, path in assets:
        with open(path, "rb") as source:
            blocks.append(format_byte_array(symbol, source.read()))
    with open(OUTPUT_INCLUDE, "w") as output:
        output.write("\n\n".join(blocks) + "\n")


def remove_bundler_sidecars():
    for name in ("titleimage.h", "titleimage.err", "saveimage.h", "saveimage.err"):
        path = os.path.join(ASSET_DIR, name)
        if os.path.isfile(path):
            os.remove(path)


def main():
    if not os.path.isfile(SOURCE_ICON):
        raise RuntimeError("Missing source icon: " + SOURCE_ICON)

    icon = Image.open(SOURCE_ICON)
    write_bitmap(icon, 128, "titleimage_128.bmp")
    write_bitmap(icon, 64, "saveimage_64.bmp")

    title_meta = "[default]\r\nTitleName={}\r\n".format(TITLE_NAME)
    with open(os.path.join(ASSET_DIR, "TitleMeta.xbx"), "wb") as output:
        output.write(codecs.BOM_UTF16_LE + title_meta.encode("utf-16le"))

    bundler = find_bundler()
    run_bundler(bundler, "titleimage.rdf")
    run_bundler(bundler, "saveimage.rdf")
    remove_bundler_sidecars()
    write_embedded_assets()

    print("Generated dashboard assets from " + SOURCE_ICON)
    print("Embedded byte include: " + OUTPUT_INCLUDE)


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print("ERROR: " + str(exc))
        sys.exit(1)
